# This workflow will install CESM, create visualCaseGen conda env, and run all CI tests.

name: visualCaseGen CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci" ]

jobs:
  ci_tests:
    name: visualCaseGen CI tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: VCG_temp
      # clone CESM
      - uses: actions/checkout@v4
        with:
          repository: alperaltuntas/CESM
          ref: cesm3_0_beta03_gui
          #submodules: recursive

      # Run git-fleximod
      - name: checkout CESM
        env:
          GIT_CLONE_PROTECTION_ACTIVE: false
        run: |
          ./bin/git-fleximod update

  
      # Checkout the correct visualCaseGen branch
      - name: Checkout initial event (Pull Request)
        run: |
          echo "Handling pull request"
          cd visualCaseGen/
          cp -r ../VCG_temp/* .

      # set up conda
      - uses: conda-incubator/setup-miniconda@v3

      # visualCaseGen conda env
      - name: Create visualCaseGen conda env
        run: |
          cd visualCaseGen/
          conda env create --file environment.yml
          conda activate visualCaseGen
    
      # Run all tests
      - name: Run tests
        env:
          CIME_MODEL: "cesm"
          CIME_DRIVER: "nuopc"
          CIME_TEST_PLATFORM: ubuntu-latest
        run: |
          export SRC_PATH="${GITHUB_WORKSPACE}"
          mkdir -p /home/runner/cesm/scratch
          cd visualCaseGen/
          conda activate visualCaseGen
          pytest tests

